pipeline {
    agent any
    environment {
        IMAGE_NAME = "python-app"
        IMAGE_TAG  = "v1"
        CONTAINER  = "python-app"
    }
    stages {
        stage('Build Docker Image') {
            steps {
                sh '''
                    cd python
                    docker build -t ${IMAGE_NAME}:${IMAGE_TAG} .
                '''
            }
        }
        stage('Stop Old Container') {
            steps {
                sh '''
                    docker stop ${CONTAINER} || true
                    docker rm ${CONTAINER} || true
                '''
            }
        }
        stage('Run Container') {
            steps {
                sh '''
                    docker run -d \
                    --name ${CONTAINER} \
                    -p 5000:5000 \
                    ${IMAGE_NAME}:${IMAGE_TAG}
                '''
            }
        }
    }
    post {
        success {
            echo "✅ Build & Deployment Successful ✅"
        }
        failure {
            echo "❌ Pipeline Failed ❌"
        }
        always {
            sh 'docker ps -a'
        }
    }
}