pipeline {
    agent any
    environment {
        IMAGE_NAME = "python-app-image"
        IMAGE_TAG  = "v1"
        CONTAINER  = "python-app-container"
    }
    options {
        skipDefaultCheckout()
    }
    stages {
        stage('Checkout & Validate') {
            steps {
                checkout scm
                script {
                    def filesChanged = sh(
                        script: '''
                            if [ -z "$(git rev-parse HEAD~1 2>/dev/null)" ]; then
                                # First commit - check all files
                                git ls-files | grep "^python/python-app/" || true
                            else
                                # Compare with previous commit
                                git diff --name-only HEAD~1 HEAD | grep "^python/python-app/" || true
                            fi
                        ''',
                        returnStdout: true
                    ).trim()
                    
                    if (filesChanged.isEmpty()) {
                        echo "❌ No changes in python/python-app directory. Aborting pipeline."
                        currentBuild.result = 'ABORTED'
                        error("Skipping: No changes in python/python-app")
                    }
                    echo "✅ Changes detected in python/python-app: ${filesChanged}"
                }
            }
        }
        stage('Build Docker New Image') {
            steps {
                sh '''
                    cd python/python-app
                    docker build -t ${IMAGE_NAME}:${IMAGE_TAG} .
                '''
            }
        }
        stage('Stop and Remove old Container') {
            steps {
                sh '''
                    docker stop ${CONTAINER} || true
                    docker rm ${CONTAINER} || true
                '''
            }
        }
        stage('Run New Container') {
            steps {
                sh '''
                    docker run -d \
                    --name ${CONTAINER} \
                    -p 5000:5000 \
                    ${IMAGE_NAME}:${IMAGE_TAG}
                '''
            }
        }
    }
    post {
        success {
            echo "Pipeline Suceeded"
        }
        failure {
            echo "Pipeline Failed"
        }
        always {
            sh 'docker ps -a'
        }
    }
}