pipeline {
    agent any
    environment {
        IMAGE_NAME = "python-app-image"
        IMAGE_TAG  = "v1"
        CONTAINER  = "python-app-container"
    }
    stages {
        stage('Validate Changes') {
            when {
                not {
                    changeset "python/python-app/**"
                }
            }
            steps {
                error("No changes in python/python-app. Build skipped.")
            }
        }
        stage('Build Docker New Image') {
            steps {
                sh '''
                    cd python/python-app
                    docker build -t ${IMAGE_NAME}:${IMAGE_TAG} .
                '''
            }
        }
        stage('Stop and Remove old Container') {
            steps {
                sh '''
                    docker stop ${CONTAINER} || true
                    docker rm ${CONTAINER} || true
                '''
            }
        }
        stage('Run New Container') {
            steps {
                sh '''
                    docker run -d \
                    --name ${CONTAINER} \
                    -p 5000:5000 \
                    ${IMAGE_NAME}:${IMAGE_TAG}
                '''
            }
        }
    }
    post {
        success {
            echo "Pipeline Suceeded"
        }
        failure {
            echo "Pipeline Failed"
        }
        always {
            sh 'docker ps -a'
        }
    }
}